const Images = {
  Logo: require('../assets/images/Logo.png'),
  comp1: require('../assets/images/comp1.png'),
  comp2: require('../assets/images/comp2.png'),
  comp3: require('../assets/images/comp3.png'),
  comp4: require('../assets/images/comp4.png'),
  comp5: require('../assets/images/comp5.png'),
  comp6: require('../assets/images/comp6.png'),
  comp7: require('../assets/images/comp7.png'),
  comp8: require('../assets/images/comp8.png'),
  comp9: require('../assets/images/comp9.png'),
  comp10: require('../assets/images/comp10.png'),
  comp11: require('../assets/images/comp11.png'),
  comp12: require('../assets/images/comp12.png'),
  comp13: require('../assets/images/comp13.png'),
  comp14: require('../assets/images/comp14.png'),
  user: require('../assets/images/user.png'),
  sample_logo: require('../assets/images/sample_logo.png'),
  image_profile: require('../assets/images/image_profile.png'),
  image2: require('../assets/images/image2.png'),
  image3: require('../assets/images/image3.png'),
  slide1: require('../assets/images/slide1.png'),
  slide2: require('../assets/images/slide2.png'),
  slide3: require('../assets/images/slide3.png'),
  user1: require('../assets/images/user1.png'),
  user2: require('../assets/images/user2.png'),
  user3: require('../assets/images/user3.png'),
  language: require('../assets/images/language.png'),
  fun: require('../assets/images/fun.png'),
  share_app: require('../assets/images/share_app.png'),

  slide_fr_1: require('../assets/images/slide_fr_1.png'),
  slide_fr_2: require('../assets/images/slide_fr_2.png'),
  slide_fr_3: require('../assets/images/slide_fr_3.png'),
};

export default Images;
